const vocabData = {
  beginner: [
    { word: "apple", meaning: "사과", example: "I eat an apple every morning." },
    { word: "banana", meaning: "바나나", example: "She likes to eat a banana for breakfast." },
    { word: "orange", meaning: "오렌지", example: "This orange is very sweet." },
    { word: "grape", meaning: "포도", example: "I bought some grapes at the market." },
    { word: "water", meaning: "물", example: "Can I have some water, please?" },
    { word: "milk", meaning: "우유", example: "I drink a glass of milk every day." },
    { word: "juice", meaning: "주스", example: "She made fresh orange juice." },
    { word: "coffee", meaning: "커피", example: "I drink coffee every morning." },
    { word: "tea", meaning: "차", example: "Would you like some tea?" },
    { word: "bread", meaning: "빵", example: "We bought fresh bread from the bakery." },
    { word: "rice", meaning: "밥, 쌀", example: "We eat rice almost every day." },
    { word: "egg", meaning: "계란", example: "I had an egg for breakfast." },
    { word: "cheese", meaning: "치즈", example: "I love cheese on my pizza." },
    { word: "meat", meaning: "고기", example: "He doesn't eat meat." },
    { word: "fish", meaning: "물고기, 생선", example: "We had fish for dinner." },
    { word: "chicken", meaning: "닭고기", example: "She cooked chicken for lunch." },
    { word: "vegetable", meaning: "채소", example: "You should eat more vegetables." },
    { word: "fruit", meaning: "과일", example: "Fruit is good for your health." },
    { word: "book", meaning: "책", example: "I am reading a good book." },
    { word: "pen", meaning: "펜", example: "Can I borrow your pen?" },
    { word: "pencil", meaning: "연필", example: "She wrote her name with a pencil." },
    { word: "paper", meaning: "종이", example: "Please write your name on the paper." },
    { word: "desk", meaning: "책상", example: "My computer is on the desk." },
    { word: "chair", meaning: "의자", example: "Please sit on this chair." },
    { word: "window", meaning: "창문", example: "Can you open the window?" },
    { word: "door", meaning: "문", example: "Please close the door." },
    { word: "table", meaning: "탁자", example: "The food is on the table." },
    { word: "bed", meaning: "침대", example: "I go to bed at ten o'clock." },
    { word: "house", meaning: "집", example: "This is my house." },
    { word: "room", meaning: "방", example: "My room is very small." },
    { word: "kitchen", meaning: "주방", example: "My mother is cooking in the kitchen." },
    { word: "bathroom", meaning: "욕실", example: "The bathroom is upstairs." },
    { word: "garden", meaning: "정원", example: "We have a beautiful garden." },
    { word: "school", meaning: "학교", example: "I go to school by bus." },
    { word: "teacher", meaning: "선생님", example: "My teacher is very kind." },
    { word: "student", meaning: "학생", example: "She is a good student." },
    { word: "friend", meaning: "친구", example: "He is my best friend." },
    { word: "family", meaning: "가족", example: "I love my family." },
    { word: "mother", meaning: "어머니", example: "My mother makes delicious food." },
    { word: "father", meaning: "아버지", example: "My father works at a bank." },
    { word: "brother", meaning: "남자형제", example: "My brother is older than me." },
    { word: "sister", meaning: "여자형제", example: "I have one sister." },
    { word: "baby", meaning: "아기", example: "The baby is sleeping." },
    { word: "child", meaning: "아이", example: "The child is playing outside." },
    { word: "man", meaning: "남자", example: "That man is my uncle." },
    { word: "woman", meaning: "여자", example: "The woman is reading a book." },
    { word: "boy", meaning: "소년", example: "The boy is playing soccer." },
    { word: "girl", meaning: "소녀", example: "The girl is singing a song." },
    { word: "dog", meaning: "개", example: "I have a cute dog." },
    { word: "cat", meaning: "고양이", example: "The cat is sleeping on the sofa." },
    { word: "bird", meaning: "새", example: "A bird is singing outside." },
    { word: "animal", meaning: "동물", example: "I like animals very much." },
    { word: "car", meaning: "자동차", example: "He drives a new car." },
    { word: "bus", meaning: "버스", example: "I take the bus to school." },
    { word: "train", meaning: "기차", example: "We took a train to Seoul." },
    { word: "airplane", meaning: "비행기", example: "The airplane arrived on time." },
    { word: "bicycle", meaning: "자전거", example: "She rides her bicycle every day." },
    { word: "taxi", meaning: "택시", example: "Let's take a taxi home." },
    { word: "street", meaning: "거리", example: "There are many shops on this street." },
    { word: "city", meaning: "도시", example: "Seoul is a big city." },
    { word: "country", meaning: "나라", example: "Korea is a beautiful country." },
    { word: "park", meaning: "공원", example: "We walked in the park." },
    { word: "store", meaning: "가게", example: "I bought some bread at the store." },
    { word: "market", meaning: "시장", example: "My mother goes to the market every week." },
    { word: "restaurant", meaning: "식당", example: "We ate dinner at a nice restaurant." },
    { word: "hospital", meaning: "병원", example: "He went to the hospital yesterday." },
    { word: "bank", meaning: "은행", example: "I need to go to the bank." },
    { word: "hotel", meaning: "호텔", example: "We stayed at a nice hotel." },
    { word: "money", meaning: "돈", example: "I don't have much money." },
    { word: "price", meaning: "가격", example: "The price of this bag is too high." },
    { word: "time", meaning: "시간", example: "What time is it now?" },
    { word: "day", meaning: "하루, 날", example: "Today is a beautiful day." },
    { word: "week", meaning: "주", example: "I will see you next week." },
    { word: "month", meaning: "월, 달", example: "This month is very busy." },
    { word: "year", meaning: "년, 해", example: "Happy new year!" },
    { word: "morning", meaning: "아침", example: "I go jogging every morning." },
    { word: "afternoon", meaning: "오후", example: "Let's meet in the afternoon." },
    { word: "evening", meaning: "저녁", example: "We had dinner in the evening." },
    { word: "night", meaning: "밤", example: "I like to read at night." },
    { word: "today", meaning: "오늘", example: "What are you doing today?" },
    { word: "tomorrow", meaning: "내일", example: "See you tomorrow." },
    { word: "yesterday", meaning: "어제", example: "I was very busy yesterday." },
    { word: "weather", meaning: "날씨", example: "The weather is nice today." },
    { word: "rain", meaning: "비", example: "It is raining outside." },
    { word: "snow", meaning: "눈", example: "It snowed a lot last night." },
    { word: "sun", meaning: "해, 태양", example: "The sun is shining brightly." },
    { word: "cloud", meaning: "구름", example: "There are many clouds in the sky." },
    { word: "wind", meaning: "바람", example: "The wind is very strong today." },
    { word: "hot", meaning: "뜨거운, 더운", example: "It is very hot today." },
    { word: "cold", meaning: "차가운, 추운", example: "It is cold outside." },
    { word: "warm", meaning: "따뜻한", example: "This blanket is very warm." },
    { word: "cool", meaning: "시원한", example: "The water is cool and refreshing." },
    { word: "big", meaning: "큰", example: "This house is very big." },
    { word: "small", meaning: "작은", example: "I live in a small apartment." },
    { word: "long", meaning: "긴", example: "Her hair is very long." },
    { word: "short", meaning: "짧은", example: "This skirt is too short." },
    { word: "tall", meaning: "키가 큰", example: "My brother is very tall." },
    { word: "new", meaning: "새로운", example: "I bought a new phone." },
    { word: "old", meaning: "오래된, 나이든", example: "This is an old building." },
    { word: "young", meaning: "어린, 젊은", example: "She looks very young." },
    { word: "good", meaning: "좋은", example: "This is a good idea." },
    { word: "bad", meaning: "나쁜", example: "That was a bad decision." },
    { word: "happy", meaning: "행복한", example: "I feel happy today." },
    { word: "sad", meaning: "슬픈", example: "She looked sad yesterday." },
    { word: "angry", meaning: "화난", example: "He was angry at me." },
    { word: "tired", meaning: "피곤한", example: "I am so tired today." },
    { word: "hungry", meaning: "배고픈", example: "I am very hungry now." },
    { word: "thirsty", meaning: "목마른", example: "I am really thirsty." },
    { word: "sick", meaning: "아픈", example: "I feel sick today." },
    { word: "busy", meaning: "바쁜", example: "I am busy this week." },
    { word: "free", meaning: "자유로운, 여유 있는", example: "Are you free this weekend?" },
    { word: "easy", meaning: "쉬운", example: "This test was very easy." },
    { word: "difficult", meaning: "어려운", example: "This question is difficult." },
    { word: "beautiful", meaning: "아름다운", example: "The sunset is beautiful." },
    { word: "pretty", meaning: "예쁜", example: "She has a pretty smile." },
    { word: "cute", meaning: "귀여운", example: "Your puppy is so cute." },
    { word: "strong", meaning: "강한", example: "He is very strong." },
    { word: "weak", meaning: "약한", example: "I feel weak today." },
    { word: "fast", meaning: "빠른", example: "He runs very fast." },
    { word: "slow", meaning: "느린", example: "The turtle is very slow." },
    { word: "eat", meaning: "먹다", example: "Let's eat lunch together." },
    { word: "drink", meaning: "마시다", example: "I drink water every day." },
    { word: "sleep", meaning: "자다", example: "I sleep at ten o'clock." },
    { word: "wake up", meaning: "일어나다", example: "I wake up at seven every day." },
    { word: "go", meaning: "가다", example: "Let's go to the park." },
    { word: "come", meaning: "오다", example: "Please come here." },
    { word: "walk", meaning: "걷다", example: "I walk to school every day." },
    { word: "run", meaning: "뛰다", example: "He runs every morning." },
    { word: "sit", meaning: "앉다", example: "Please sit down." },
    { word: "stand", meaning: "서다", example: "Please stand up." },
    { word: "read", meaning: "읽다", example: "I like to read books." },
    { word: "write", meaning: "쓰다", example: "She is writing a letter." },
    { word: "speak", meaning: "말하다", example: "Can you speak English?" },
    { word: "listen", meaning: "듣다", example: "I like to listen to music." },
    { word: "see", meaning: "보다", example: "I can see the mountain from here." },
    { word: "watch", meaning: "보다(시청)", example: "We watched a movie last night." },
    { word: "look", meaning: "보다", example: "Look at this picture." },
    { word: "buy", meaning: "사다", example: "I want to buy a new bag." },
    { word: "sell", meaning: "팔다", example: "They sell fresh vegetables here." },
    { word: "open", meaning: "열다", example: "Please open the door." },
    { word: "close", meaning: "닫다", example: "Please close the window." },
    { word: "start", meaning: "시작하다", example: "The movie will start soon." },
    { word: "finish", meaning: "끝내다", example: "I finished my homework." },
    { word: "help", meaning: "돕다", example: "Can you help me, please?" },
    { word: "like", meaning: "좋아하다", example: "I like coffee very much." },
    { word: "love", meaning: "사랑하다", example: "I love my family." },
    { word: "want", meaning: "원하다", example: "I want to learn English." },
    { word: "need", meaning: "필요하다", example: "I need some water." },
    { word: "know", meaning: "알다", example: "I know his name." },
    { word: "think", meaning: "생각하다", example: "I think this is a good idea." },
    { word: "feel", meaning: "느끼다", example: "I feel happy today." },
    { word: "make", meaning: "만들다", example: "She made a cake for me." },
    { word: "do", meaning: "하다", example: "What are you doing now?" },
    { word: "play", meaning: "놀다, 연주하다", example: "The children are playing outside." },
    { word: "work", meaning: "일하다", example: "I work every day." },
    { word: "study", meaning: "공부하다", example: "I study English every night." },
    { word: "teach", meaning: "가르치다", example: "She teaches math at school." },
    { word: "learn", meaning: "배우다", example: "I want to learn English." },
    { word: "live", meaning: "살다", example: "I live in Seoul." },
    { word: "cook", meaning: "요리하다", example: "My father cooks dinner every Sunday." },
    { word: "clean", meaning: "청소하다", example: "I clean my room every weekend." },
    { word: "wash", meaning: "씻다", example: "Please wash your hands." },
    { word: "wear", meaning: "입다", example: "She is wearing a red dress." },
    { word: "shirt", meaning: "셔츠", example: "He is wearing a blue shirt." },
    { word: "pants", meaning: "바지", example: "These pants are too long." },
    { word: "shoes", meaning: "신발", example: "I need new shoes." },
    { word: "hat", meaning: "모자", example: "He is wearing a hat." },
    { word: "dress", meaning: "원피스, 드레스", example: "She bought a new dress." },
    { word: "jacket", meaning: "재킷", example: "I need a warm jacket." },
    { word: "color", meaning: "색깔", example: "What color do you like?" },
    { word: "red", meaning: "빨간색", example: "I like the red car." },
    { word: "blue", meaning: "파란색", example: "The sky is blue." },
    { word: "green", meaning: "초록색", example: "The grass is green." },
    { word: "yellow", meaning: "노란색", example: "The banana is yellow." },
    { word: "black", meaning: "검은색", example: "He is wearing black shoes." },
    { word: "white", meaning: "흰색", example: "She has a white cat." },
    { word: "one", meaning: "하나", example: "I have one brother." },
    { word: "two", meaning: "둘", example: "I have two sisters." },
    { word: "three", meaning: "셋", example: "There are three books on the desk." },
    { word: "ten", meaning: "열", example: "I have ten dollars." },
    { word: "hundred", meaning: "백", example: "This bag costs a hundred dollars." },
    { word: "Monday", meaning: "월요일", example: "I have a meeting on Monday." },
    { word: "Sunday", meaning: "일요일", example: "We go to church on Sunday." },
    { word: "spring", meaning: "봄", example: "I love the spring season." },
    { word: "summer", meaning: "여름", example: "Summer is very hot in Korea." },
    { word: "autumn", meaning: "가을", example: "The leaves change color in autumn." },
    { word: "winter", meaning: "겨울", example: "It snows a lot in winter." },
    { word: "music", meaning: "음악", example: "I like listening to music." },
    { word: "movie", meaning: "영화", example: "Let's watch a movie tonight." },
    { word: "game", meaning: "게임", example: "The children are playing a game." },
    { word: "phone", meaning: "전화기", example: "My phone is out of battery." },
    { word: "computer", meaning: "컴퓨터", example: "I use my computer every day." },
    { word: "television", meaning: "텔레비전", example: "We watched television last night." },
    { word: "letter", meaning: "편지", example: "She wrote a letter to her friend." },
    { word: "picture", meaning: "그림, 사진", example: "This is a picture of my family." },
    { word: "name", meaning: "이름", example: "What is your name?" },
    { word: "address", meaning: "주소", example: "Can you give me your address?" },
    { word: "number", meaning: "숫자, 번호", example: "What is your phone number?" },
    { word: "question", meaning: "질문", example: "Can I ask you a question?" },
    { word: "answer", meaning: "대답", example: "I don't know the answer." }
  ],
  intermediate: [
    { word: "achieve", meaning: "성취하다", example: "She worked hard to achieve her goal." },
    { word: "opportunity", meaning: "기회", example: "This is a great opportunity for you." },
    { word: "decision", meaning: "결정", example: "I need to make a decision soon." },
    { word: "experience", meaning: "경험", example: "That was a valuable experience for me." },
    { word: "environment", meaning: "환경", example: "We should protect the environment." },
    { word: "improve", meaning: "개선하다", example: "I want to improve my English skills." },
    { word: "relationship", meaning: "관계", example: "They have a good relationship." },
    { word: "responsibility", meaning: "책임", example: "It's your responsibility to finish it." },
    { word: "confident", meaning: "자신감 있는", example: "He looks confident on stage." },
    { word: "suggest", meaning: "제안하다", example: "Can you suggest a good restaurant?" },
    { word: "compare", meaning: "비교하다", example: "Let's compare the two options." },
    { word: "explain", meaning: "설명하다", example: "Could you explain that again?" },
    { word: "schedule", meaning: "일정", example: "My schedule is very busy this week." },
    { word: "challenge", meaning: "도전", example: "Learning a new language is a challenge." },
    { word: "focus", meaning: "집중하다", example: "I need to focus on my work." },
    { word: "benefit", meaning: "이익", example: "This plan has many benefits." },
    { word: "avoid", meaning: "피하다", example: "Try to avoid making mistakes." },
    { word: "appreciate", meaning: "감사하다", example: "I really appreciate your help." },
    { word: "increase", meaning: "증가하다", example: "The company decided to increase prices next month." },
    { word: "decrease", meaning: "감소하다", example: "Sales decreased significantly last year." },
    { word: "develop", meaning: "발전시키다, 개발하다", example: "We need to develop a new strategy." },
    { word: "development", meaning: "발전, 개발", example: "This is an important development in technology." },
    { word: "discover", meaning: "발견하다", example: "Scientists discovered a new species." },
    { word: "discovery", meaning: "발견", example: "It was an amazing discovery." },
    { word: "produce", meaning: "생산하다", example: "The factory produces thousands of cars a year." },
    { word: "production", meaning: "생산", example: "Production costs have increased this year." },
    { word: "reduce", meaning: "줄이다", example: "We should reduce our expenses." },
    { word: "reduction", meaning: "감소", example: "There was a reduction in staff last month." },
    { word: "describe", meaning: "묘사하다, 설명하다", example: "Can you describe what happened?" },
    { word: "description", meaning: "설명, 묘사", example: "The job description was very clear." },
    { word: "include", meaning: "포함하다", example: "The price includes breakfast." },
    { word: "exclude", meaning: "제외하다", example: "Please exclude this item from the list." },
    { word: "require", meaning: "필요로 하다", example: "This job requires good communication skills." },
    { word: "requirement", meaning: "요구사항", example: "There are several requirements for this position." },
    { word: "provide", meaning: "제공하다", example: "The hotel provides free breakfast." },
    { word: "prevent", meaning: "예방하다, 막다", example: "Regular exercise can prevent many diseases." },
    { word: "protect", meaning: "보호하다", example: "We need to protect our environment." },
    { word: "protection", meaning: "보호", example: "This cream provides sun protection." },
    { word: "support", meaning: "지지하다, 지원하다", example: "My family always supports me." },
    { word: "succeed", meaning: "성공하다", example: "She succeeded in passing the exam." },
    { word: "success", meaning: "성공", example: "Hard work is the key to success." },
    { word: "successful", meaning: "성공적인", example: "The project was very successful." },
    { word: "fail", meaning: "실패하다", example: "He failed the driving test twice." },
    { word: "failure", meaning: "실패", example: "Failure is part of the learning process." },
    { word: "attempt", meaning: "시도하다, 시도", example: "She made an attempt to fix the problem." },
    { word: "achievement", meaning: "성취, 업적", example: "Graduating was a huge achievement for him." },
    { word: "continue", meaning: "계속하다", example: "Please continue with your presentation." },
    { word: "continuous", meaning: "지속적인", example: "There has been continuous improvement." },
    { word: "complete", meaning: "완료하다, 완전한", example: "Please complete this form." },
    { word: "completely", meaning: "완전히", example: "I completely agree with you." },
    { word: "depend", meaning: "의존하다", example: "It depends on the weather." },
    { word: "dependent", meaning: "의존하는", example: "Children are dependent on their parents." },
    { word: "independent", meaning: "독립적인", example: "She is very independent." },
    { word: "encourage", meaning: "격려하다", example: "Teachers should encourage students to ask questions." },
    { word: "discourage", meaning: "좌절시키다, 막다", example: "Don't let failure discourage you." },
    { word: "celebrate", meaning: "축하하다", example: "We celebrated her birthday yesterday." },
    { word: "celebration", meaning: "축하, 기념", example: "The celebration lasted all night." },
    { word: "communicate", meaning: "의사소통하다", example: "It's important to communicate clearly." },
    { word: "communication", meaning: "의사소통", example: "Good communication is key to success." },
    { word: "cooperate", meaning: "협력하다", example: "The two countries agreed to cooperate." },
    { word: "cooperation", meaning: "협력", example: "Thank you for your cooperation." },
    { word: "participate", meaning: "참여하다", example: "Everyone is encouraged to participate." },
    { word: "participation", meaning: "참여", example: "Participation in this event is free." },
    { word: "organize", meaning: "조직하다, 준비하다", example: "She organized the entire event." },
    { word: "organization", meaning: "조직, 기관", example: "He works for a non-profit organization." },
    { word: "manage", meaning: "관리하다", example: "She manages a large team." },
    { word: "management", meaning: "관리, 경영", example: "Time management is important." },
    { word: "manager", meaning: "관리자", example: "He was promoted to manager last year." },
    { word: "employ", meaning: "고용하다", example: "The company employs over 500 people." },
    { word: "employee", meaning: "직원", example: "All employees must wear an ID badge." },
    { word: "employer", meaning: "고용주", example: "My employer gave me a bonus." },
    { word: "employment", meaning: "고용", example: "She found employment at a local bank." },
    { word: "unemployment", meaning: "실업", example: "Unemployment is a serious issue." },
    { word: "career", meaning: "경력, 직업", example: "She has a successful career in medicine." },
    { word: "skill", meaning: "기술, 능력", example: "Good communication skills are essential." },
    { word: "ability", meaning: "능력", example: "He has the ability to solve complex problems." },
    { word: "talent", meaning: "재능", example: "She has a talent for painting." },
    { word: "knowledge", meaning: "지식", example: "He has a lot of knowledge about history." },
    { word: "education", meaning: "교육", example: "Education is very important for children." },
    { word: "educate", meaning: "교육하다", example: "Parents should educate their children about safety." },
    { word: "university", meaning: "대학교", example: "She studies at a famous university." },
    { word: "degree", meaning: "학위", example: "He has a degree in economics." },
    { word: "graduate", meaning: "졸업하다, 졸업생", example: "She graduated from university last year." },
    { word: "graduation", meaning: "졸업", example: "Graduation day was very emotional." },
    { word: "lecture", meaning: "강의", example: "The professor gave an interesting lecture." },
    { word: "professor", meaning: "교수", example: "My professor is very knowledgeable." },
    { word: "classmate", meaning: "반 친구", example: "She met her classmate at the cafe." },
    { word: "semester", meaning: "학기", example: "This semester has been very busy." },
    { word: "exam", meaning: "시험", example: "I have a big exam next week." },
    { word: "grade", meaning: "성적, 학년", example: "She got a good grade on the test." },
    { word: "score", meaning: "점수", example: "He got a perfect score on the exam." },
    { word: "report", meaning: "보고서, 보고하다", example: "I need to finish this report by Friday." },
    { word: "project", meaning: "프로젝트, 과제", example: "We are working on a new project." },
    { word: "presentation", meaning: "발표", example: "I have to give a presentation tomorrow." },
    { word: "document", meaning: "문서", example: "Please sign this document." },
    { word: "contract", meaning: "계약", example: "They signed a contract yesterday." },
    { word: "agreement", meaning: "합의, 계약", example: "We finally reached an agreement." },
    { word: "negotiate", meaning: "협상하다", example: "They negotiated a better price." },
    { word: "negotiation", meaning: "협상", example: "The negotiation took several hours." }
  ],
  advanced: [
    { word: "ambiguous", meaning: "모호한", example: "The instructions were quite ambiguous." },
    { word: "inevitable", meaning: "불가피한", example: "Change is inevitable in life." },
    { word: "controversial", meaning: "논란이 많은", example: "That's a controversial topic." },
    { word: "sophisticated", meaning: "세련된, 정교한", example: "She has sophisticated taste in art." },
    { word: "persistent", meaning: "끈질긴", example: "He was persistent in his efforts." },
    { word: "skeptical", meaning: "회의적인", example: "I'm skeptical about that theory." },
    { word: "comprehensive", meaning: "포괄적인", example: "We need a comprehensive plan." },
    { word: "deteriorate", meaning: "악화되다", example: "The situation began to deteriorate." },
    { word: "subsequent", meaning: "그 다음의", example: "The subsequent meeting was cancelled." },
    { word: "profound", meaning: "심오한", example: "He made a profound impact on society." },
    { word: "reluctant", meaning: "꺼리는", example: "She was reluctant to answer the question." },
    { word: "arbitrary", meaning: "임의적인", example: "The decision seemed completely arbitrary." },
    { word: "meticulous", meaning: "세심한", example: "He is meticulous about details." },
    { word: "resilient", meaning: "회복력 있는", example: "Children are often surprisingly resilient." },
    { word: "paradox", meaning: "역설", example: "It's a strange paradox of modern life." },
    { word: "mitigate", meaning: "완화하다", example: "We must mitigate the risks." },
    { word: "eloquent", meaning: "유창한", example: "She gave an eloquent speech." },
    { word: "discrepancy", meaning: "차이, 불일치", example: "There is a discrepancy in the reports." },
    { word: "underlying", meaning: "근본적인", example: "We need to find the underlying cause." },
    { word: "plausible", meaning: "타당한", example: "That explanation seems plausible." },
    { word: "ubiquitous", meaning: "어디에나 있는", example: "Smartphones have become ubiquitous." },
    { word: "pragmatic", meaning: "실용적인", example: "We need a pragmatic approach to this problem." },
    { word: "empirical", meaning: "경험적인, 실증적인", example: "The study is based on empirical evidence." },
    { word: "hypothesis", meaning: "가설", example: "Scientists tested their hypothesis carefully." },
    { word: "theoretical", meaning: "이론적인", example: "This is a theoretical explanation, not a practical one." },
    { word: "methodology", meaning: "방법론", example: "The research methodology was very rigorous." },
    { word: "paradigm", meaning: "패러다임, 전형", example: "This discovery created a new paradigm." },
    { word: "phenomenon", meaning: "현상", example: "Climate change is a global phenomenon." },
    { word: "anomaly", meaning: "이례적인 것, 변칙", example: "The data showed an unusual anomaly." },
    { word: "correlation", meaning: "상관관계", example: "There is a strong correlation between the two factors." },
    { word: "causation", meaning: "인과관계", example: "Correlation does not always imply causation." },
    { word: "inference", meaning: "추론", example: "We made an inference based on the evidence." },
    { word: "deduction", meaning: "추론, 공제", example: "His deduction was based on careful observation." },
    { word: "presumption", meaning: "추정", example: "It was a reasonable presumption to make." },
    { word: "assumption", meaning: "가정", example: "We made an assumption that turned out to be wrong." },
    { word: "implication", meaning: "함의, 영향", example: "The implications of this decision are serious." },
    { word: "connotation", meaning: "함축된 의미", example: "That word has a negative connotation." },
    { word: "denotation", meaning: "명시적 의미", example: "The denotation of the word is quite simple." },
    { word: "nuance", meaning: "미묘한 차이", example: "There is a subtle nuance between these two words." },
    { word: "subtlety", meaning: "미묘함", example: "The subtlety of her argument impressed everyone." },
    { word: "ambivalent", meaning: "양가적인, 애매한", example: "I feel ambivalent about this decision." },
    { word: "indifferent", meaning: "무관심한", example: "He seemed indifferent to the outcome." },
    { word: "apathetic", meaning: "무관심한", example: "Many young people feel apathetic about politics." },
    { word: "empathetic", meaning: "공감하는", example: "She is very empathetic toward others." },
    { word: "altruistic", meaning: "이타적인", example: "His altruistic behavior surprised everyone." },
    { word: "egocentric", meaning: "자기중심적인", example: "His egocentric attitude annoyed his coworkers." },
    { word: "narcissistic", meaning: "자기애가 강한", example: "His narcissistic behavior pushed people away." },
    { word: "pretentious", meaning: "가식적인", example: "The restaurant's menu felt a bit pretentious." },
    { word: "condescending", meaning: "거만한", example: "His condescending tone upset the students." },
    { word: "patronizing", meaning: "잘난 체하는", example: "Please don't be patronizing when you explain this." },
    { word: "derogatory", meaning: "비하하는", example: "He made a derogatory comment about her work." },
    { word: "disparaging", meaning: "비하하는", example: "She made disparaging remarks about his idea." },
    { word: "laudatory", meaning: "칭찬하는", example: "The review was extremely laudatory." },
    { word: "commendable", meaning: "훌륭한, 칭찬할 만한", example: "Her effort was truly commendable." },
    { word: "exemplary", meaning: "모범적인", example: "He received an award for exemplary service." },
    { word: "unprecedented", meaning: "전례 없는", example: "The company faced unprecedented challenges this year." },
    { word: "unparalleled", meaning: "비할 데 없는", example: "Her success in the field was unparalleled." },
    { word: "formidable", meaning: "강력한, 만만찮은", example: "They faced a formidable opponent in the final." },
    { word: "daunting", meaning: "위압적인, 벅찬", example: "The task seemed daunting at first." },
    { word: "intimidating", meaning: "위협적인", example: "His tall stature can be intimidating." },
    { word: "overwhelming", meaning: "압도적인", example: "The support from fans was overwhelming." },
    { word: "exhilarating", meaning: "매우 신나는", example: "The roller coaster ride was exhilarating." },
    { word: "invigorating", meaning: "활력을 주는", example: "A morning walk can be invigorating." },
    { word: "tedious", meaning: "지루한", example: "Filling out these forms is tedious." },
    { word: "monotonous", meaning: "단조로운", example: "The lecture was long and monotonous." },
    { word: "mundane", meaning: "평범한, 일상적인", example: "He was tired of his mundane daily routine." },
    { word: "redundant", meaning: "불필요한, 중복된", example: "This sentence contains a redundant phrase." },
    { word: "superfluous", meaning: "여분의, 불필요한", example: "Remove any superfluous details from the report." },
    { word: "extraneous", meaning: "관련 없는", example: "Please avoid extraneous information in your essay." },
    { word: "peripheral", meaning: "주변적인", example: "This is only a peripheral issue, not the main one." },
    { word: "tangential", meaning: "주제와 관련 없는", example: "His comment was tangential to the discussion." },
    { word: "integral", meaning: "필수적인", example: "Trust is integral to any relationship." },
    { word: "fundamental", meaning: "근본적인", example: "Honesty is a fundamental value in this company." },
    { word: "quintessential", meaning: "전형적인", example: "He is the quintessential example of a hard worker." },
    { word: "archetypal", meaning: "전형적인, 원형적인", example: "She plays the archetypal hero in the story." },
    { word: "prototypical", meaning: "대표적인, 전형적인", example: "This design is prototypical of the era." },
    { word: "idiosyncratic", meaning: "개인 특유의", example: "He has an idiosyncratic way of speaking." },
    { word: "eccentric", meaning: "특이한, 별난", example: "The artist was known for his eccentric behavior." },
    { word: "unconventional", meaning: "관습에 얽매이지 않는", example: "She took an unconventional approach to the problem." },
    { word: "unorthodox", meaning: "정통이 아닌", example: "His unorthodox methods surprised his colleagues." },
    { word: "heretical", meaning: "이단적인", example: "His ideas were considered heretical at the time." },
    { word: "dogmatic", meaning: "독단적인", example: "He has a dogmatic attitude toward tradition." },
    { word: "doctrinaire", meaning: "교조적인", example: "Her doctrinaire views made compromise difficult." },
    { word: "authoritarian", meaning: "권위주의적인", example: "The country was ruled by an authoritarian government." },
    { word: "egalitarian", meaning: "평등주의적인", example: "They believe in an egalitarian society." },
    { word: "utilitarian", meaning: "실용주의적인", example: "His approach to design is highly utilitarian." },
    { word: "altruism", meaning: "이타주의", example: "Altruism is at the core of volunteer work." },
    { word: "hedonism", meaning: "쾌락주의", example: "His lifestyle reflects a philosophy of hedonism." },
    { word: "stoicism", meaning: "인내, 스토아 철학", example: "She faced the crisis with remarkable stoicism." },
    { word: "nihilism", meaning: "허무주의", example: "His novels often explore themes of nihilism." },
    { word: "cynicism", meaning: "냉소주의", example: "Years of disappointment led to his cynicism." },
    { word: "optimism", meaning: "낙관주의", example: "Her optimism inspired the whole team." },
    { word: "pessimism", meaning: "비관주의", example: "His pessimism made the meeting feel gloomy." },
    { word: "fatalism", meaning: "운명론", example: "His fatalism made him accept every outcome calmly." },
    { word: "determinism", meaning: "결정론", example: "Determinism suggests that all events are predetermined." },
    { word: "autonomy", meaning: "자율성", example: "Employees value autonomy in their work." },
    { word: "sovereignty", meaning: "주권", example: "The country fought hard for its sovereignty." },
    { word: "jurisdiction", meaning: "관할권", example: "This case falls under federal jurisdiction." },
    { word: "legislation", meaning: "법률, 입법", example: "New legislation was passed last month." },
    { word: "litigation", meaning: "소송", example: "The company is currently involved in litigation." }
  ]
};

const speakingData = {
  beginner: [
    { sentence: "Hello, how are you today?", meaning: "안녕하세요, 오늘 어떠세요?" },
    { sentence: "My name is Tom. Nice to meet you.", meaning: "제 이름은 톰입니다. 만나서 반가워요." },
    { sentence: "I like coffee in the morning.", meaning: "저는 아침에 커피를 좋아해요." },
    { sentence: "What time is it now?", meaning: "지금 몇 시예요?" },
    { sentence: "The weather is very nice today.", meaning: "오늘 날씨가 정말 좋네요." },
    { sentence: "I am going to the store.", meaning: "저는 가게에 가는 중이에요." },
    { sentence: "Can you help me, please?", meaning: "저를 도와주실 수 있나요?" },
    { sentence: "I love spending time with my family.", meaning: "저는 가족과 시간을 보내는 것을 좋아해요." },
    { sentence: "This food tastes really good.", meaning: "이 음식은 정말 맛있어요." },
    { sentence: "I usually wake up at seven.", meaning: "저는 보통 7시에 일어나요." },
    { sentence: "Where is the nearest bus stop?", meaning: "가장 가까운 버스 정류장이 어디예요?" },
    { sentence: "I want to learn English well.", meaning: "저는 영어를 잘 배우고 싶어요." },
    { sentence: "See you tomorrow at school.", meaning: "내일 학교에서 봐요." },
    { sentence: "Thank you very much for your help.", meaning: "도와주셔서 정말 감사해요." },
    { sentence: "What is your favorite color?", meaning: "가장 좋아하는 색이 뭐예요?" },
    { sentence: "I have two brothers and one sister.", meaning: "저는 형제 둘, 자매 한 명이 있어요." },
    { sentence: "Can I have a glass of water?", meaning: "물 한 잔 마실 수 있을까요?" },
    { sentence: "I go to work by subway.", meaning: "저는 지하철로 출근해요." },
    { sentence: "This is my favorite restaurant.", meaning: "여기가 제가 가장 좋아하는 식당이에요." },
    { sentence: "How much does this cost?", meaning: "이거 얼마예요?" },
    { sentence: "I need to buy some groceries.", meaning: "저는 장을 좀 봐야 해요." },
    { sentence: "Let's meet at the coffee shop.", meaning: "커피숍에서 만나요." },
    { sentence: "I really enjoy watching movies.", meaning: "저는 영화 보는 걸 정말 좋아해요." },
    { sentence: "My favorite season is autumn.", meaning: "제가 가장 좋아하는 계절은 가을이에요." },
    { sentence: "Could you repeat that, please?", meaning: "다시 말씀해 주시겠어요?" },
    { sentence: "I'm learning English every day.", meaning: "저는 매일 영어를 배우고 있어요." },
    { sentence: "Do you have any brothers or sisters?", meaning: "형제나 자매가 있나요?" },
    { sentence: "I'm going to bed early tonight.", meaning: "저는 오늘 밤 일찍 자려고 해요." },
    { sentence: "Can you speak more slowly, please?", meaning: "좀 더 천천히 말씀해 주시겠어요?" },
    { sentence: "I enjoy listening to music on weekends.", meaning: "저는 주말에 음악 듣는 걸 좋아해요." },
    { sentence: "What do you usually do on weekends?", meaning: "주말에는 보통 뭐 하세요?" },
    { sentence: "I'm looking for a good restaurant nearby.", meaning: "근처에 좋은 식당을 찾고 있어요." },
    { sentence: "It's raining, so bring an umbrella.", meaning: "비가 오니까 우산을 챙기세요." },
    { sentence: "I really need a cup of coffee.", meaning: "저는 커피가 정말 필요해요." },
    { sentence: "Let's go for a walk in the park.", meaning: "공원에서 산책하러 가요." },
    { sentence: "I'm so excited about the trip.", meaning: "여행이 정말 기대돼요." },
    { sentence: "Could you tell me the way to the station?", meaning: "역으로 가는 길을 알려주실 수 있나요?" },
    { sentence: "I usually have cereal for breakfast.", meaning: "저는 보통 아침에 시리얼을 먹어요." },
    { sentence: "My phone battery is almost dead.", meaning: "제 휴대폰 배터리가 거의 다 됐어요." },
    { sentence: "I'm planning to visit my grandmother this weekend.", meaning: "저는 이번 주말에 할머니를 방문할 계획이에요." },
    { sentence: "Do you want to grab lunch together?", meaning: "같이 점심 먹으러 갈래요?" },
    { sentence: "I forgot my umbrella at home.", meaning: "저는 집에 우산을 두고 왔어요." },
    { sentence: "Can you turn off the lights, please?", meaning: "불을 좀 꺼주시겠어요?" },
    { sentence: "I'm feeling a little tired today.", meaning: "저는 오늘 좀 피곤해요." },
    { sentence: "What's your favorite kind of music?", meaning: "가장 좋아하는 음악 종류가 뭐예요?" },
    { sentence: "I need to charge my phone.", meaning: "저는 휴대폰을 충전해야 해요." },
    { sentence: "Let's order some pizza for dinner.", meaning: "저녁으로 피자를 시켜요." },
    { sentence: "I take a shower every morning.", meaning: "저는 매일 아침 샤워를 해요." },
    { sentence: "This bag is too heavy for me.", meaning: "이 가방은 저에게 너무 무거워요." },
    { sentence: "I'm going to clean my room today.", meaning: "저는 오늘 제 방을 청소할 거예요." },
    { sentence: "Could you pass me the salt, please?", meaning: "소금 좀 건네주시겠어요?" },
    { sentence: "I like to read before I go to sleep.", meaning: "저는 자기 전에 책 읽는 걸 좋아해요." },
    { sentence: "My favorite subject in school was math.", meaning: "학교에서 제가 가장 좋아했던 과목은 수학이었어요." },
    { sentence: "I'm going to call my mother later.", meaning: "저는 나중에 어머니께 전화할 거예요." },
    { sentence: "Can we watch a movie tonight?", meaning: "오늘 밤에 영화 볼까요?" },
    { sentence: "I like walking my dog in the evening.", meaning: "저는 저녁에 강아지를 산책시키는 걸 좋아해요." },
    { sentence: "This coat keeps me very warm.", meaning: "이 코트는 저를 매우 따뜻하게 해줘요." },
    { sentence: "I'm saving money to buy a new laptop.", meaning: "저는 새 노트북을 사려고 돈을 모으고 있어요." },
    { sentence: "Could you show me how to get there?", meaning: "그곳에 가는 방법을 알려주실 수 있나요?" },
    { sentence: "I really appreciate your kindness.", meaning: "당신의 친절함에 정말 감사해요." }
  ],
  intermediate: [
    { sentence: "I've been trying to improve my English skills lately.", meaning: "저는 최근에 영어 실력을 향상시키려고 노력하고 있어요." },
    { sentence: "Could you give me some advice about this problem?", meaning: "이 문제에 대해 조언을 좀 해주실 수 있나요?" },
    { sentence: "I think we should consider other options first.", meaning: "먼저 다른 선택지들을 고려해봐야 할 것 같아요." },
    { sentence: "It was a great opportunity to learn something new.", meaning: "새로운 것을 배울 수 있는 좋은 기회였어요." },
    { sentence: "I'm a little nervous about the presentation tomorrow.", meaning: "내일 발표 때문에 조금 긴장돼요." },
    { sentence: "She decided to change her career last year.", meaning: "그녀는 작년에 직업을 바꾸기로 결심했어요." },
    { sentence: "We need to focus on the most important tasks.", meaning: "우리는 가장 중요한 일에 집중해야 해요." },
    { sentence: "I really appreciate everything you've done for me.", meaning: "당신이 저를 위해 해준 모든 것에 정말 감사해요." },
    { sentence: "It's important to maintain a good relationship with coworkers.", meaning: "동료들과 좋은 관계를 유지하는 것이 중요해요." },
    { sentence: "He suggested that we meet again next week.", meaning: "그는 우리가 다음 주에 다시 만나자고 제안했어요." },
    { sentence: "I'm planning to travel abroad this summer.", meaning: "저는 이번 여름에 해외 여행을 계획하고 있어요." },
    { sentence: "The traffic was terrible, so I arrived late.", meaning: "교통이 너무 안 좋아서 늦게 도착했어요." },
    { sentence: "I'd like to compare these two products before buying.", meaning: "구매하기 전에 이 두 제품을 비교해보고 싶어요." },
    { sentence: "Let's schedule a meeting for next Monday.", meaning: "다음 주 월요일로 회의 일정을 잡아요." },
    { sentence: "I need to submit this report by the end of the day.", meaning: "저는 오늘 안에 이 보고서를 제출해야 해요." },
    { sentence: "She has been working on this project for months.", meaning: "그녀는 몇 달째 이 프로젝트를 진행하고 있어요." },
    { sentence: "I'm not sure if this decision is the right one.", meaning: "이 결정이 옳은지 잘 모르겠어요." },
    { sentence: "We should communicate more clearly with the team.", meaning: "우리는 팀과 더 명확하게 소통해야 해요." },
    { sentence: "He always encourages his students to try their best.", meaning: "그는 항상 학생들에게 최선을 다하라고 격려해요." },
    { sentence: "I'm trying to save money for a new car.", meaning: "저는 새 차를 사기 위해 돈을 모으고 있어요." },
    { sentence: "The negotiation took longer than we expected.", meaning: "협상은 예상보다 오래 걸렸어요." },
    { sentence: "I really need to manage my time better.", meaning: "저는 시간을 더 잘 관리해야 해요." },
    { sentence: "She graduated from university with honors.", meaning: "그녀는 우등으로 대학교를 졸업했어요." },
    { sentence: "It's difficult to balance work and personal life.", meaning: "일과 개인 생활의 균형을 맞추는 것이 어려워요." },
    { sentence: "I'm worried about the increasing cost of living.", meaning: "저는 늘어나는 생활비가 걱정돼요." },
    { sentence: "We finally reached an agreement after a long discussion.", meaning: "긴 논의 끝에 우리는 마침내 합의에 도달했어요." },
    { sentence: "He was promoted to manager after two years.", meaning: "그는 2년 후에 관리자로 승진했어요." },
    { sentence: "I'm trying to develop better study habits.", meaning: "저는 더 나은 공부 습관을 기르려고 노력하고 있어요." },
    { sentence: "This job requires excellent communication skills.", meaning: "이 직업은 훌륭한 의사소통 능력을 필요로 해요." },
    { sentence: "She always supports her friends during hard times.", meaning: "그녀는 힘든 시기에 항상 친구들을 지지해줘요." },
    { sentence: "I'm considering applying for a new position.", meaning: "저는 새로운 직책에 지원할지 고민하고 있어요." },
    { sentence: "The company decided to reduce its expenses this year.", meaning: "그 회사는 올해 비용을 줄이기로 결정했어요." },
    { sentence: "He explained the situation very clearly to everyone.", meaning: "그는 모두에게 상황을 매우 명확하게 설명했어요." },
    { sentence: "I'd like to participate in this volunteer program.", meaning: "저는 이 자원봉사 프로그램에 참여하고 싶어요." },
    { sentence: "We should celebrate her achievement together.", meaning: "우리는 그녀의 성취를 함께 축하해야 해요." },
    { sentence: "It's important to protect our personal information online.", meaning: "온라인에서 개인 정보를 보호하는 것이 중요해요." },
    { sentence: "She has a lot of experience in marketing.", meaning: "그녀는 마케팅 분야에서 경험이 많아요." },
    { sentence: "I need to prepare a presentation for tomorrow's meeting.", meaning: "저는 내일 회의를 위한 발표를 준비해야 해요." },
    { sentence: "He failed the exam, but he didn't give up.", meaning: "그는 시험에 떨어졌지만 포기하지 않았어요." },
    { sentence: "I'm trying to reduce my stress levels.", meaning: "저는 스트레스 수치를 줄이려고 노력하고 있어요." },
    { sentence: "The company provides excellent employee benefits.", meaning: "그 회사는 훌륭한 직원 복지를 제공해요." },
    { sentence: "I think honesty is essential in any relationship.", meaning: "저는 정직함이 어떤 관계에서든 필수적이라고 생각해요." },
    { sentence: "She organized the entire conference by herself.", meaning: "그녀는 그 컨퍼런스 전체를 혼자서 조직했어요." },
    { sentence: "We need to discuss the budget for next quarter.", meaning: "우리는 다음 분기 예산에 대해 논의해야 해요." },
    { sentence: "I'm confident that we can solve this problem together.", meaning: "저는 우리가 이 문제를 함께 해결할 수 있다고 확신해요." },
    { sentence: "He always takes responsibility for his mistakes.", meaning: "그는 항상 자신의 실수에 대해 책임을 져요." },
    { sentence: "The teacher encouraged us to ask more questions.", meaning: "선생님은 우리에게 더 많은 질문을 하도록 격려했어요." },
    { sentence: "I'm trying to find a good work-life balance.", meaning: "저는 좋은 워라밸을 찾으려고 노력하고 있어요." },
    { sentence: "She succeeded in starting her own business.", meaning: "그녀는 자신의 사업을 시작하는 데 성공했어요." },
    { sentence: "We should avoid making the same mistake twice.", meaning: "우리는 같은 실수를 두 번 하지 않도록 피해야 해요." },
    { sentence: "I really value your opinion on this matter.", meaning: "저는 이 문제에 대한 당신의 의견을 정말 중요하게 생각해요." },
    { sentence: "He invested a lot of money in that company.", meaning: "그는 그 회사에 많은 돈을 투자했어요." },
    { sentence: "I'm looking forward to the upcoming conference.", meaning: "저는 다가오는 컨퍼런스를 기대하고 있어요." },
    { sentence: "The economy has improved significantly this year.", meaning: "올해 경제가 상당히 개선되었어요." },
    { sentence: "She always manages to stay calm under pressure.", meaning: "그녀는 압박 속에서도 항상 침착함을 유지해요." },
    { sentence: "I need to renew my contract before it expires.", meaning: "저는 계약이 만료되기 전에 갱신해야 해요." },
    { sentence: "We should cooperate more closely with other departments.", meaning: "우리는 다른 부서들과 더 긴밀하게 협력해야 해요." },
    { sentence: "He has a talent for solving complex problems.", meaning: "그는 복잡한 문제를 해결하는 재능이 있어요." },
    { sentence: "I appreciate your patience while we sort this out.", meaning: "이 문제를 해결하는 동안 인내해주셔서 감사해요." },
    { sentence: "It's essential to keep learning throughout your career.", meaning: "경력 전반에 걸쳐 계속 배우는 것이 필수적이에요." }
  ],
  advanced: [
    { sentence: "The situation has become increasingly complicated over the past few months.", meaning: "지난 몇 달 동안 상황이 점점 더 복잡해졌어요." },
    { sentence: "I understand your concerns, but I believe there's a more effective approach.", meaning: "당신의 우려를 이해하지만, 더 효과적인 방법이 있다고 생각해요." },
    { sentence: "Despite the challenges, the team managed to complete the project successfully.", meaning: "어려움에도 불구하고 팀은 프로젝트를 성공적으로 완료했어요." },
    { sentence: "It's difficult to predict how the market will react to this change.", meaning: "이 변화에 시장이 어떻게 반응할지 예측하기 어려워요." },
    { sentence: "Her argument was compelling, but I remain somewhat skeptical.", meaning: "그녀의 주장은 설득력이 있었지만, 저는 여전히 좀 회의적이에요." },
    { sentence: "We should thoroughly analyze the underlying causes before making a decision.", meaning: "결정을 내리기 전에 근본적인 원인을 철저히 분석해야 해요." },
    { sentence: "The company is trying to mitigate the risks associated with this investment.", meaning: "그 회사는 이 투자와 관련된 위험을 완화하려고 노력하고 있어요." },
    { sentence: "His explanation, though eloquent, failed to address the core issue.", meaning: "그의 설명은 유창했지만 핵심 문제를 다루지는 못했어요." },
    { sentence: "There seems to be a significant discrepancy between the two reports.", meaning: "두 보고서 사이에 상당한 차이가 있는 것 같아요." },
    { sentence: "I found it rather paradoxical that success sometimes leads to more stress.", meaning: "성공이 때로는 더 많은 스트레스로 이어진다는 것이 다소 역설적이라고 느꼈어요." },
    { sentence: "The negotiations were tense, but both sides remained reasonably flexible.", meaning: "협상은 긴장감이 있었지만 양측 모두 비교적 유연했어요." },
    { sentence: "It's important to remain resilient in the face of unexpected setbacks.", meaning: "예상치 못한 어려움 앞에서도 회복력을 유지하는 것이 중요해요." },
    { sentence: "The proposal, while ambitious, lacks a comprehensive implementation plan.", meaning: "그 제안은 야심적이지만 포괄적인 실행 계획이 부족해요." },
    { sentence: "Ultimately, we need to reach a decision that benefits everyone involved.", meaning: "결국 우리는 관련된 모든 사람에게 이익이 되는 결정을 내려야 해요." },
    { sentence: "The policy change has had a profound impact on small businesses.", meaning: "그 정책 변화는 소규모 사업체에 심오한 영향을 미쳤어요." },
    { sentence: "It would be naive to assume that this solution has no drawbacks.", meaning: "이 해결책에 단점이 없다고 가정하는 것은 순진한 생각일 거예요." },
    { sentence: "The research findings raise more questions than they answer.", meaning: "그 연구 결과는 답보다 더 많은 질문을 제기해요." },
    { sentence: "Her meticulous attention to detail set her apart from other candidates.", meaning: "그녀의 세심한 디테일에 대한 주의는 다른 지원자들과 차별화시켰어요." },
    { sentence: "The company's unprecedented growth has attracted a lot of attention.", meaning: "그 회사의 전례 없는 성장은 많은 관심을 끌었어요." },
    { sentence: "We must consider the long-term implications of this policy.", meaning: "우리는 이 정책의 장기적인 함의를 고려해야 해요." },
    { sentence: "His pragmatic approach helped the team overcome numerous obstacles.", meaning: "그의 실용적인 접근 방식은 팀이 수많은 장애물을 극복하도록 도왔어요." },
    { sentence: "The evidence strongly suggests a correlation between the two factors.", meaning: "그 증거는 두 요인 사이의 강한 상관관계를 시사해요." },
    { sentence: "It's crucial to maintain objectivity when evaluating controversial issues.", meaning: "논란이 많은 문제를 평가할 때 객관성을 유지하는 것이 중요해요." },
    { sentence: "The committee reached a unanimous decision after extensive deliberation.", meaning: "위원회는 광범위한 심의 후 만장일치로 결정을 내렸어요." },
    { sentence: "Her reluctance to compromise made the negotiation more difficult.", meaning: "그녀가 타협을 꺼려한 것이 협상을 더 어렵게 만들었어요." },
    { sentence: "The economic downturn had a ripple effect across multiple industries.", meaning: "경기 침체는 여러 산업에 연쇄적인 영향을 미쳤어요." },
    { sentence: "We need to distinguish between correlation and causation in this analysis.", meaning: "이 분석에서는 상관관계와 인과관계를 구별해야 해요." },
    { sentence: "His argument, though logically sound, overlooked several key nuances.", meaning: "그의 주장은 논리적으로 타당했지만 몇 가지 중요한 미묘함을 간과했어요." },
    { sentence: "The organization is committed to fostering an inclusive work environment.", meaning: "그 조직은 포용적인 근무 환경을 조성하는 데 전념하고 있어요." },
    { sentence: "It's imperative that we address this issue before it escalates further.", meaning: "이 문제가 더 확대되기 전에 반드시 해결해야 해요." },
    { sentence: "The findings of the study were largely consistent with previous research.", meaning: "그 연구 결과는 이전 연구와 대체로 일치했어요." },
    { sentence: "Her unconventional approach to leadership yielded surprising results.", meaning: "그녀의 관습에 얽매이지 않는 리더십 접근 방식은 놀라운 결과를 낳았어요." },
    { sentence: "The government implemented several measures to curb inflation.", meaning: "정부는 인플레이션을 억제하기 위해 여러 조치를 시행했어요." },
    { sentence: "His cynicism about the project's success proved to be unfounded.", meaning: "그 프로젝트의 성공에 대한 그의 냉소주의는 근거 없는 것으로 드러났어요." },
    { sentence: "We should approach this challenge with both caution and optimism.", meaning: "우리는 신중함과 낙관주의를 모두 가지고 이 도전에 접근해야 해요." },
    { sentence: "The report highlighted several discrepancies in the financial statements.", meaning: "그 보고서는 재무제표의 여러 불일치를 강조했어요." },
    { sentence: "Her ability to articulate complex ideas clearly is truly remarkable.", meaning: "복잡한 아이디어를 명확하게 표현하는 그녀의 능력은 정말 놀라워요." },
    { sentence: "The debate revealed a fundamental disagreement about core values.", meaning: "그 토론은 핵심 가치에 대한 근본적인 의견 차이를 드러냈어요." },
    { sentence: "It's essential to critically evaluate the credibility of your sources.", meaning: "출처의 신뢰성을 비판적으로 평가하는 것이 필수적이에요." },
    { sentence: "His persistent efforts eventually led to a breakthrough in the research.", meaning: "그의 끈질긴 노력은 결국 연구에서 돌파구를 만들어냈어요." },
    { sentence: "The merger raised concerns about potential monopolistic practices.", meaning: "그 합병은 독점적 관행에 대한 우려를 불러일으켰어요." },
    { sentence: "We need a more nuanced understanding of the cultural context.", meaning: "우리는 문화적 맥락에 대한 더 세밀한 이해가 필요해요." },
    { sentence: "Her skepticism toward the new policy was shared by many colleagues.", meaning: "새로운 정책에 대한 그녀의 회의적인 태도는 많은 동료들도 공감했어요." },
    { sentence: "The recovery process has been slower than initially anticipated.", meaning: "회복 과정은 처음 예상했던 것보다 더 느렸어요." },
    { sentence: "It's worth considering the ethical implications of this technology.", meaning: "이 기술의 윤리적 함의를 고려해볼 필요가 있어요." },
    { sentence: "His argument was undermined by a lack of empirical evidence.", meaning: "그의 주장은 실증적 증거의 부족으로 설득력이 약화되었어요." },
    { sentence: "The initiative aims to promote sustainability across all departments.", meaning: "그 계획은 모든 부서에 걸쳐 지속 가능성을 촉진하는 것을 목표로 해요." },
    { sentence: "We must be cautious not to draw premature conclusions from limited data.", meaning: "제한된 데이터로부터 성급한 결론을 내리지 않도록 주의해야 해요." },
    { sentence: "The controversy surrounding the decision has not yet subsided.", meaning: "그 결정을 둘러싼 논란은 아직 가라앉지 않았어요." },
    { sentence: "Her resilience in the face of adversity inspired her entire team.", meaning: "역경에 맞선 그녀의 회복력은 팀 전체에 영감을 주었어요." },
    { sentence: "The policy has inadvertently created several unintended consequences.", meaning: "그 정책은 의도치 않게 몇 가지 예상치 못한 결과를 초래했어요." },
    { sentence: "It's important to differentiate between symptoms and root causes.", meaning: "증상과 근본 원인을 구별하는 것이 중요해요." },
    { sentence: "His meticulous planning ensured the project stayed on schedule.", meaning: "그의 세심한 계획은 프로젝트가 일정대로 진행되도록 보장했어요." },
    { sentence: "The debate over the policy has become increasingly polarized.", meaning: "그 정책에 대한 논쟁은 점점 더 양극화되고 있어요." },
    { sentence: "We should remain open-minded even when confronting unfamiliar perspectives.", meaning: "익숙하지 않은 관점에 맞닥뜠을 때도 열린 마음을 유지해야 해요." },
    { sentence: "The evidence, while compelling, is not entirely conclusive.", meaning: "그 증거는 설득력이 있지만 완전히 결정적이지는 않아요." },
    { sentence: "Her contribution to the project was invaluable and often underappreciated.", meaning: "그녀의 프로젝트에 대한 기여는 매우 귀중했지만 종종 과소평가되었어요." },
    { sentence: "The organization is undergoing a significant structural transformation.", meaning: "그 조직은 중요한 구조적 변화를 겪고 있어요." },
    { sentence: "It's crucial to strike a balance between innovation and stability.", meaning: "혁신과 안정성 사이의 균형을 맞추는 것이 중요해요." },
    { sentence: "His unwavering determination ultimately led to a remarkable achievement.", meaning: "그의 변함없는 결단력은 결국 놀라운 성취로 이어졌어요." }
  ]
};
