const vocabData = {
  beginner: [
    { word: "apple", meaning: "사과", example: "I eat an apple every morning." },
    { word: "book", meaning: "책", example: "I am reading a book." },
    { word: "water", meaning: "물", example: "Can I have some water?" },
    { word: "friend", meaning: "친구", example: "She is my best friend." },
    { word: "happy", meaning: "행복한", example: "I feel happy today." },
    { word: "school", meaning: "학교", example: "I go to school by bus." },
    { word: "family", meaning: "가족", example: "I love my family." },
    { word: "work", meaning: "일하다, 일", example: "I work every day." },
    { word: "eat", meaning: "먹다", example: "Let's eat lunch together." },
    { word: "sleep", meaning: "자다", example: "I sleep at ten o'clock." },
    { word: "house", meaning: "집", example: "This is my house." },
    { word: "money", meaning: "돈", example: "I need some money." },
    { word: "time", meaning: "시간", example: "What time is it?" },
    { word: "day", meaning: "날, 하루", example: "Today is a good day." },
    { word: "weather", meaning: "날씨", example: "The weather is nice today." },
    { word: "movie", meaning: "영화", example: "Let's watch a movie tonight." },
    { word: "music", meaning: "음악", example: "I like listening to music." },
    { word: "car", meaning: "자동차", example: "He drives a new car." },
    { word: "food", meaning: "음식", example: "Korean food is delicious." },
    { word: "rain", meaning: "비", example: "It is raining outside." }
  ],
  intermediate: [
    { word: "achieve", meaning: "성취하다", example: "She worked hard to achieve her goal." },
    { word: "opportunity", meaning: "기회", example: "This is a great opportunity for you." },
    { word: "decision", meaning: "결정", example: "I need to make a decision." },
    { word: "experience", meaning: "경험", example: "That was a valuable experience." },
    { word: "environment", meaning: "환경", example: "We should protect the environment." },
    { word: "improve", meaning: "개선하다, 향상시키다", example: "I want to improve my English." },
    { word: "relationship", meaning: "관계", example: "They have a good relationship." },
    { word: "responsibility", meaning: "책임", example: "It's your responsibility to finish it." },
    { word: "confident", meaning: "자신 있는", example: "He looks confident on stage." },
    { word: "suggest", meaning: "제안하다", example: "Can you suggest a good restaurant?" },
    { word: "compare", meaning: "비교하다", example: "Let's compare the two options." },
    { word: "explain", meaning: "설명하다", example: "Could you explain that again?" },
    { word: "schedule", meaning: "일정", example: "My schedule is very busy this week." },
    { word: "challenge", meaning: "도전, 난제", example: "Learning a new language is a challenge." },
    { word: "focus", meaning: "집중하다", example: "I need to focus on my work." },
    { word: "benefit", meaning: "이익, 혜택", example: "This plan has many benefits." },
    { word: "avoid", meaning: "피하다", example: "Try to avoid making mistakes." },
    { word: "appreciate", meaning: "감사하다, 고마워하다", example: "I really appreciate your help." },
    { word: "flexible", meaning: "유연한", example: "You should be flexible with your plans." },
    { word: "consider", meaning: "고려하다", example: "Please consider my suggestion." }
  ],
  advanced: [
    { word: "ambiguous", meaning: "모호한", example: "The instructions were quite ambiguous." },
    { word: "inevitable", meaning: "불가피한", example: "Change is inevitable in life." },
    { word: "controversial", meaning: "논란이 많은", example: "That's a controversial topic." },
    { word: "sophisticated", meaning: "세련된, 정교한", example: "She has a sophisticated taste in art." },
    { word: "persistent", meaning: "끈질긴, 지속적인", example: "He was persistent in his efforts." },
    { word: "skeptical", meaning: "회의적인", example: "I'm skeptical about that theory." },
    { word: "comprehensive", meaning: "포괄적인", example: "We need a comprehensive plan." },
    { word: "deteriorate", meaning: "악화되다", example: "The situation began to deteriorate." },
    { word: "subsequent", meaning: "그 다음의, 후속의", example: "The subsequent meeting was cancelled." },
    { word: "profound", meaning: "심오한, 깊은", example: "He made a profound impact on society." },
    { word: "reluctant", meaning: "꺼리는, 주저하는", example: "She was reluctant to answer the question." },
    { word: "arbitrary", meaning: "임의적인", example: "The decision seemed completely arbitrary." },
    { word: "meticulous", meaning: "세심한, 꼼꼼한", example: "He is meticulous about details." },
    { word: "resilient", meaning: "회복력 있는", example: "Children are often surprisingly resilient." },
    { word: "paradox", meaning: "역설, 모순", example: "It's a strange paradox of modern life." },
    { word: "mitigate", meaning: "완화하다", example: "We must mitigate the risks." },
    { word: "eloquent", meaning: "유창한, 설득력 있는", example: "She gave an eloquent speech." },
    { word: "discrepancy", meaning: "차이, 불일치", example: "There is a discrepancy in the reports." },
    { word: "underlying", meaning: "근본적인, 근원적인", example: "We need to find the underlying cause." },
    { word: "plausible", meaning: "타당한, 그럴듯한", example: "That explanation seems plausible." }
  ]
};

const speakingData = {
  beginner: [
    { sentence: "Hello, how are you today?", meaning: "안녕하세요, 오늘 어떠세요?" },
    { sentence: "My name is Tom. Nice to meet you.", meaning: "제 이름은 톰입니다. 만나서 반가워요." },
    { sentence: "I like coffee in the morning.", meaning: "저는 아침에 커피를 좋아해요." },
    { sentence: "What time is it now?", meaning: "지금 몇 시예요?" },
    { sentence: "The weather is very nice today.", meaning: "오늘 날씨가 정말 좋네요." },
    { sentence: "I am going to the store.", meaning: "저는 가게에 가는 중이에요." },
    { sentence: "Can you help me, please?", meaning: "저를 도와주실 수 있나요?" },
    { sentence: "I love spending time with my family.", meaning: "저는 가족과 시간을 보내는 것을 좋아해요." },
    { sentence: "This food tastes really good.", meaning: "이 음식은 정말 맛있어요." },
    { sentence: "I usually wake up at seven.", meaning: "저는 보통 7시에 일어나요." },
    { sentence: "Where is the nearest bus stop?", meaning: "가장 가까운 버스 정류장이 어디예요?" },
    { sentence: "I want to learn English well.", meaning: "저는 영어를 잘 배우고 싶어요." },
    { sentence: "See you tomorrow at school.", meaning: "내일 학교에서 봐요." },
    { sentence: "Thank you very much for your help.", meaning: "도와주셔서 정말 감사해요." }
  ],
  intermediate: [
    { sentence: "I've been trying to improve my English skills lately.", meaning: "저는 최근에 영어 실력을 향상시키려고 노력하고 있어요." },
    { sentence: "Could you give me some advice about this problem?", meaning: "이 문제에 대해 조언을 좀 해주실 수 있나요?" },
    { sentence: "I think we should consider other options first.", meaning: "먼저 다른 선택지들을 고려해봐야 할 것 같아요." },
    { sentence: "It was a great opportunity to learn something new.", meaning: "새로운 것을 배울 수 있는 좋은 기회였어요." },
    { sentence: "I'm a little nervous about the presentation tomorrow.", meaning: "내일 발표 때문에 조금 긴장돼요." },
    { sentence: "She decided to change her career last year.", meaning: "그녀는 작년에 직업을 바꾸기로 결심했어요." },
    { sentence: "We need to focus on the most important tasks.", meaning: "우리는 가장 중요한 일에 집중해야 해요." },
    { sentence: "I really appreciate everything you've done for me.", meaning: "당신이 저를 위해 해준 모든 것에 정말 감사해요." },
    { sentence: "It's important to maintain a good relationship with coworkers.", meaning: "동료들과 좋은 관계를 유지하는 것이 중요해요." },
    { sentence: "He suggested that we meet again next week.", meaning: "그는 우리가 다음 주에 다시 만나자고 제안했어요." },
    { sentence: "I'm planning to travel abroad this summer.", meaning: "저는 이번 여름에 해외 여행을 계획하고 있어요." },
    { sentence: "The traffic was terrible, so I arrived late.", meaning: "교통이 너무 안 좋아서 늦게 도착했어요." },
    { sentence: "I'd like to compare these two products before buying.", meaning: "구매하기 전에 이 두 제품을 비교해보고 싶어요." },
    { sentence: "Let's schedule a meeting for next Monday.", meaning: "다음 주 월요일로 회의 일정을 잡아요." }
  ],
  advanced: [
    { sentence: "The situation has become increasingly complicated over the past few months.", meaning: "지난 몇 달 동안 상황이 점점 더 복잡해졌어요." },
    { sentence: "I understand your concerns, but I believe there's a more effective approach.", meaning: "당신의 우려를 이해하지만, 더 효과적인 방법이 있다고 생각해요." },
    { sentence: "Despite the challenges, the team managed to complete the project successfully.", meaning: "어려움에도 불구하고 팀은 프로젝트를 성공적으로 완료했어요." },
    { sentence: "It's difficult to predict how the market will react to this change.", meaning: "이 변화에 시장이 어떻게 반응할지 예측하기 어려워요." },
    { sentence: "Her argument was compelling, but I remain somewhat skeptical.", meaning: "그녀의 주장은 설득력이 있었지만, 저는 여전히 좀 회의적이에요." },
    { sentence: "We should thoroughly analyze the underlying causes before making a decision.", meaning: "결정을 내리기 전에 근본적인 원인을 철저히 분석해야 해요." },
    { sentence: "The company is trying to mitigate the risks associated with this investment.", meaning: "그 회사는 이 투자와 관련된 위험을 완화하려고 노력하고 있어요." },
    { sentence: "His explanation, though eloquent, failed to address the core issue.", meaning: "그의 설명은 유창했지만 핵심 문제를 다루지는 못했어요." },
    { sentence: "There seems to be a significant discrepancy between the two reports.", meaning: "두 보고서 사이에 상당한 차이가 있는 것 같아요." },
    { sentence: "I found it rather paradoxical that success sometimes leads to more stress.", meaning: "성공이 때로는 더 많은 스트레스로 이어진다는 것이 다소 역설적이라고 느꼈어요." },
    { sentence: "The negotiations were tense, but both sides remained reasonably flexible.", meaning: "협상은 긴장감이 있었지만 양측 모두 비교적 유연했어요." },
    { sentence: "It's important to remain resilient in the face of unexpected setbacks.", meaning: "예상치 못한 어려움 앞에서도 회복력을 유지하는 것이 중요해요." },
    { sentence: "The proposal, while ambitious, lacks a comprehensive implementation plan.", meaning: "그 제안은 야심적이지만 포괄적인 실행 계획이 부족해요." },
    { sentence: "Ultimately, we need to reach a decision that benefits everyone involved.", meaning: "결국 우리는 관련된 모든 사람에게 이익이 되는 결정을 내려야 해요." }
  ]
};
